### PR TITLE
Make it possible to relax strict Gherkin scenario validation

### LINKED ISSUE #118: Allowing when steps to follow then steps?
While it is generally good practice to order steps Given/When/Then it can sometimes be expedient to check conditions part way through a complex scenario (e.g. a multi-page form.)

I think the ordering checks in [feature.py](https://github.com/pytest-dev/pytest-bdd/blob/2.10.0/pytest_bdd/feature.py#L222) should be relaxed.

Cucumber [doesn't distinguish between step types](https://github.com/cucumber/cucumber/wiki/Given-When-Then) internally and does not enforce ordering. With behave one can register for all keywords using the ``step()`` decorator and ordering is not enforced.

### PR DESCRIPTION
**Pull request by bubenkoff**
closes #118. closes #119

### CODE REVIEW

**Comment by lrowe** [comment]
This doesn't work when the ``pytestbdd_strict_gherkin`` fixture is set in a conftest.py.

**Comment by lrowe** [comment]
It also doesn't work with the ``scenarios`` helper when the fixture is in the test file.

**Comment by lrowe** [comment]
Also needs to handle steps in background.

**Comment by bubenkoff** [comment]
my god, so your background contains something else than given?

**Comment by bubenkoff** [comment]
what's your code, please show the structure

**Comment by lrowe** [comment]
Currently we have a feature like this:
```cucumber
Feature: Search
    Background:
        When I visit "/search"
        And I wait for the content to load

    Scenario: Search
        Then the title should contain the text "Search"

    Scenario: Search Antibodies
        When I click the link with text that contains "Data"
        And I click the link to "/search/?type=antibody_lot"
        And I wait for the content to load
        Then I should see at least 15 elements with the css selector "ul.nav.result-table > li"
        And I should see at least 5 elements with the css selector "div.box.facets > div.facet"
        ...
```

**Comment by bubenkoff** [comment]
fixed in 2.12.1 please check

**Comment by lrowe** [comment]
My tests still fail with 2.12.1 because the ``pytestbdd_strict_gherkin`` fixture is not respected when using ``scenarios``.

**Comment by bubenkoff** [comment]
Right, sorry i forgot to fix that as well. Will do today

**Comment by bubenkoff** [comment]
2.12.2 is out, please try

**Comment by lrowe** [comment]
Thanks @bubenkoff. This is now working for me with the scenarios helper and the fixture in conftest.py.

**Pull request merged**
