### PR TITLE
Fix #202: replace step parameters by their values in --gherkin-terminal-reporter output

### LINKED ISSUE #202: --gherkin-terminal-reporter does not print examples data in outline scenario
I am using to run my test the amazing command " --gherkin-terminal-reporter "; 

Unfortunately it seems that actually it prints good scenario steps; but not their examples data.

Here is an example:

Suppose this is my scenario:

```
Feature: Login
    Scenario Outline: Login as a user
        Given I log in as <user>
        Then login done
  
   Examples:
       | user      |
       | user_one  |
       | user_two  |

```

=> My Actual printed result is:
```

Feature: Login
    Scenario: Login as a user
        Given I log in as <user>
        Then login done
PASSED

Feature: Login
    Scenario: Login as a user
        Given I log in as <user>
        Then login done
PASSED
 

```

=> Desired result:
```

Feature: Login
    Scenario: Login as a user
        Given I log in as user_one 
        Then login done
PASSED

Feature: Login
    Scenario: Login as a user
        Given I log in as user_two
        Then login done
PASSED
 
```

### PR DESCRIPTION
**Pull request by pauk-slon**
Fix #202. The output with real values from examples looks much nicer.

---
This change is [Reviewable](https://reviewable.io/reviews/pytest-dev/pytest-bdd/222)

### CODE REVIEW

**Comment by glennergeerts** [comment]
Is there a chance this PR will be merged? This would certainly improve the usability of the output when using `--gherkin-terminal-reporter` imo.

**Comment by olegpidsadnyi** [comment]
@pauk-slon, @glennergeerts  there was a similar one: https://github.com/pytest-dev/pytest-bdd/pull/227/files
As far as I know there's a flag in cucumber for this expanded format.
Shouldn't this one also have something like --gherkin-terminal-reporter-expanded to enable this formatting?
Parameter substitution is a good thing, but looking up the step by the name (definition) is also a useful thing. I think this should be optional. Like in cucumber formatter

**Comment by pauk-slon** [comment]
@olegpidsadnyi I updated my PR according your comment.

**Comment by olegpidsadnyi** [comment]
:lgtm:

---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/pytest-dev/pytest-bdd/222#-:-L9FwLFp6GG_W6AOOZCa:bnfp4nl)*

**Pull request merged**
