### PR TITLE
Fix generate-missing for parsed fixtures

### LINKED ISSUE #414: Generate missing doesn't work for parsed fixtures
Running `pytest --generate-missing --feature features/my-feature.feature` does not take parsed fixtures into account. This is problematic as parsed given/when/then fixtures are super helpful to capture a lot of parametrized test cases 😅

This issue is related to PR #361 although as it's a year old it might be too stale to merge in safely.

### PR DESCRIPTION
**Pull request by AntoineDao**
This should resolve #414 and trump #361.

### CODE REVIEW

**Comment by AntoineDao** [comment]
So like... I know it says the tests have failed. But in reality, all the tests have passed and what failed was [some linting step for `python3.8`](https://travis-ci.org/github/pytest-dev/pytest-bdd/jobs/766475536#L438). Can we count this as passing tests? 😅

**Comment by AntoineDao** [comment]
@youtux any chance you could look over this PR to confirm whether the fix makes sense and is desirable?

**Comment by youtux** [comment]
Thank you for the PR, I'll get back to this later when I have some more time. The fix is definitively desirable, I just need more time to check the implementation.

In the meantime, you can fix the failing linting issue by
```shell
pip install black && black tests/generation/test_generate_missing.py
```

This project uses pre-commit to run automated actions before each commit, you can install it and then run
```shell
pre-commit
```
so that the code formatter (black) is run automatically on all the files staged.

**Comment by AntoineDao** [comment]
Oh, thanks for running the linting for me on this one 🙌 Let me know if there's anything else I can do to help get this PR merged in. Thanks for the great testing tool by the way ❤

**Comment by youtux** [comment]
@olegpidsadnyi can you check this? @AntoineDao made the original fix, I made some modifications afterward.

**Review by olegpidsadnyi — APPROVED** [review]

**Pull request merged**
