### PR TITLE
better parsing of comments, fix #99

### LINKED ISSUE #99: # is unconditionally treated as a comment starter
There should be a way to escape a # or even better, if it is inside quotes or on a table it should be treated as data.

### PR DESCRIPTION
**Pull request by santagada**

### CODE REVIEW

**Comment by santagada** [comment]
I couldn't get tests to run...

**Comment by santagada** [comment]
I found out what was my problem... I'm fixing the problems and refreshing this pull request

**Comment by bubenkoff** [comment]
this is very nice improvement!

please add changelog entry and rebase to have single commit

**Comment by santagada** [comment]
done :)

**Comment by bubenkoff** [comment]
thanks a lot!

2.6.2 is out

**Pull request merged**
