### PR TITLE
Merged version of the gherkin reporter

### PR DESCRIPTION
**Pull request by thedrow**
This is an updated version of #147 that is merged against the current master.
I finally have some time to work on this so I'll do my best to ensure this will be merged in.

### CODE REVIEW

**Comment by thedrow** [comment]
@The-Compiler Can you take a look at the build? I didn't change anything in tox but one of the jobs won't run.

**Comment by The-Compiler** [comment]
@thedrow The bitbucket -> github move of pylib broke this, #197 should fix it.

**Comment by The-Compiler** [comment]
I merged it and did a rerun of this PR, all green now!

**Comment by thedrow** [comment]
Can we merge this PR as is and improve it later?

**Comment by olegpidsadnyi** [comment]
Looks fine. @The-Compiler what do you think? Merge?

**Comment by The-Compiler** [comment]
It seems to conflict though :wink: LGTM from a very quick look, but I don't have time for a closer review today.

**Comment by thedrow** [comment]
I just merged again.
I think this is good to go. We need to open issues about the plugins this conflicts with and try to make them work but otherwise, it looks good.

**Comment by olegpidsadnyi** [comment]
Would be nice to refactor the test folder structure though. Now report-related tests are in the feature folder, etc...

**Comment by thedrow** [comment]
@olegpidsadnyi @The-Compiler Can we please release this?

**Comment by olegpidsadnyi** [comment]
https://pypi.python.org/pypi/pytest-bdd/2.18.0

**Pull request merged**
