### PR TITLE
Add gettext support

### PR DESCRIPTION
**Pull request by dutradda**
First translation was written for portuguese, according to https://cucumber.io/docs/gherkin/reference/#spoken-languages.

The PR also enables the language reset during runtime.

### CODE REVIEW

**Comment by dutradda** [comment]
@youtux, @olegpidsadnyi and @sliwinski-milosz 

Hello guys,
can any of you take a look on my PR?

I have to change the tox/travis settings because the pytest 4.5 and after are crashing the tests.

**Comment by sliwinski-milosz** [comment]
Travis has been fixed on master so you can revert your travis related changes

**Comment by dutradda** [comment]
@sliwinski-milosz 
code updated

**Comment by olegpidsadnyi** [comment]
To be honest I don't really understand why do we need gettext for 11 keywords. This seems like an overkill. Another point is the current language. I think this should be a pytest option that the plugin introduces.

**Comment by olegpidsadnyi** [comment]
The whole point is to be compatible with the cucumber? To let people use pytetst instead of cucumber? Then the language support is like this:
https://cucumber.io/docs/gherkin/reference/#spoken-languages

#language header, and only keywords. There's no need in gettext. This is just a simple dict lookup once the header is set on the feature file. Otherwise english.

See https://github.com/cucumber/gherkin-python/blob/master/gherkin/gherkin-languages.json

**Comment by youtux** [comment]
Maybe we should instead import and use [gherkin](https://pypi.org/project/gherkin-official) and delegate the parsing of feature files to this library, provided by cucumber.io.
If we use that, we will have automatic support for all the languages, and issues like #311 would probably not exist, or they would have to be fixed by the upstream.

**Comment by dutradda** [comment]
@olegpidsadnyi and @youtux 
How we can proceed?

I really want to see multiple languages support on `pytest-bdd`. We already written the feature files in portuguese here. And the Gherkin language recommends that.

I can change my PR to fit the needs of the project.
But I need to know the next steps.

**Comment by youtux** [comment]
@dutradda, if you are willing to work on this, I would propose to continue in this way:

1. add the dependency to `gherkin-official` to this project
2. parse feature files with that library, instead of having our own parsing logic

I am not sure how much work it would require, but I think it is a viable option.

**Comment by dutradda** [comment]
@youtux 
I'll do it and keep you informed

**Comment by jsa34** [comment]
@youtux is this still relevant/needed?

**Comment by youtux** [comment]
> @youtux is this still relevant/needed?

Now that we use the official parser it should come out of the box. https://github.com/pytest-dev/pytest-bdd/pull/698


maybe we should add a test though to make sure that everything work fine when using a feature file in  a different language

**Comment by jsa34** [comment]
Good point.  I've got a few other issues that just need asserting and tests to close them.  I'll add this to them

**Comment by jsa34** [comment]
@youtux I don't think this is needed if we are using the official parser and should probably use the gherkin languages.json as a lookup for gherkin syntax?

**Comment by jsa34** [comment]
Localisation now supported.  This PR has been superseded.

**Pull request closed without merging**
