### PR TITLE
cast "values" as a string because it could be another type if using e…

### PR DESCRIPTION
**Pull request by marcbrossaissogeti**
#324 --cucumberjson-expanded does not work for pytest.mark.parametrize

To make it clearer:
The method "_format_name" in cucumber_json.py is using another method which expect all parameters to be strings. If you use example converters, the argument could be an other type.

I have fixed the behavior by only casting the parameter : 
```python
    name = name.replace("<{}>".format(param), str(value))
```

### CODE REVIEW

**Comment by marcbrossaissogeti** [comment]
up ? @youtux it should be easy to integrate

**Comment by youtux** [comment]
Hi @marcbrossaissogeti, thank you for the fix. Can you add a test for it?

**Comment by ishmelev23** [comment]
The problem still exists. Why it hasn't been merged, yet?

**Comment by youtux** [comment]
@ishmelev23 I missed the updates to this PR. It's merged now.
@marcbrossaissogeti thanks for the PR.

**Pull request merged**
