### PR TITLE
Test all supported pytest versions (plus more python interpreters)

### PR DESCRIPTION
**Pull request by youtux**
Test all the supported pytest versions (and latest pytest on all the supported python interpreters) and re-enable pytest-xdist in tox.ini and on trevis.

### CODE REVIEW

**Comment by youtux** [comment]
@bubenkoff I could even enable all the combinations between interpreters and pytest versions on travis (i.e. `py{27,34,35,36,37}-pytest{29,30,31,32,33,34,35,36,37,38,39,latest}`). Please let me know what you think.

**Comment by youtux** [comment]
I don't really see the point in testing against the master (unreleased) version of pytest, since it may have bugs that are not solved yet, and that would fail our build.
The reason behind testing for non-latest pytest releases is that sometimes we break compatibility (see https://github.com/pytest-dev/pytest-bdd/pull/260 for example) and this change would catch that.
We also have to explicitly maintain different implementation for some specific functions according to the pytest version (see https://github.com/pytest-dev/pytest-bdd/pull/262 for example). Without this change, we would only be testing the behavior of pytest-bdd with pytest > 3.6, but we would not cover the behaviour for pytest < 3.6.

**Comment by bubenkoff** [comment]
the reason for testing master is to catch problems with released versions sooner
but i agree it's not critical
regarding older pytest versions, why can't we just stay on the latest pytest?
breaking compartibility is ok as soon as correct version requirement is there for pytest
the thing is, it makes support of pytest-bdd so much more problematic if we keep supporting multiple pytest versions

**Comment by youtux** [comment]
Sometimes it gets quite difficult to upgrade pytest dependency on a project that use many pytest plugins and many pytest internals. That's why IMO we should not assume that everybody is using always latest pytest.

**Comment by bubenkoff** [comment]
@youtux i see, ok
regarding making a huge matrix of different pythons and pytests i think it would be an overkill
so your changes are fine with me

**Pull request merged**
