### PR TITLE
Test tags on multiple lines now handled correctly

### LINKED ISSUE #194: Multiple lines with tags override previous lines
When I have `foo.feature`:

``` python
Feature: Test

    @tag1
    @tag2
    Scenario: Test
        When foo
        Then bar
```

and `foo.py`:

``` python
from pytest_bdd import scenarios, when, then

@when('foo')
def when_foo():
    pass

@then('bar')
def then_bar():
    pass

scenarios('foo.feature')
```

I'd expect the scenario to be tagged with both `tag1` and `tag2` - however, the second tag line just overrides the first:

```
$ py.test foo.py -ktag1
=============== test session starts ===============
platform linux -- Python 3.5.2, pytest-2.9.2, py-1.4.31, pluggy-0.3.1
rootdir: /home/florian/bdd, inifile: 
plugins: bdd-2.17.0
collected 1 items 

========= 1 tests deselected by '-ktag1' ==========
========== 1 deselected in 0.02 seconds ===========
```

```
$ py.test foo.py -ktag2
=============== test session starts ===============
platform linux -- Python 3.5.2, pytest-2.9.2, py-1.4.31, pluggy-0.3.1
rootdir: /home/florian/bdd, inifile: 
plugins: bdd-2.17.0
collected 1 items 

foo.py .

============ 1 passed in 0.02 seconds =============
```

### PR DESCRIPTION
**Pull request by jsa34**
Resolves #194

### CODE REVIEW

**Review by youtux — APPROVED** [review]
Nice one

**Comment by youtux** [comment]
test is failing with `py3.11-pytest6.2-coverage`, can you double check?

**Comment by jsa34** [comment]
It's my test syntax with pytest 6.  What's the minimum supported version of pytest we support?  It doesn't seem as clear cut as python's support cycle.

**Comment by youtux** [comment]
we can drop pytest 6.2 compatibility, as it's quite old (released in 2021).

We should indeed declare the pytest requirement in `pyproject.yaml`

**Review by youtux — APPROVED** [review]

**Pull request merged**
